.TH textmode-lifestyle 1 "January 5, 2017"
.SH NAME
textmode-lifestyle \- Scaleable text-mode intro demo for the Linux terminal.
.PP
.SH SYNOPSIS
textmode-lifestyle
.PP
.SH DESCRIPTION
Non-interactive demo for the Linux terminal. The main logo is changed depending on the terminal geometry (in order to fit). Escape quits the demo instantly.
.PP
.SH BUGS
No known.
.PP
.SH AUTHOR
schnitz (https://github.com/schnitz81)
